name: cloud-config-service
replicas: 1

image: ${artifact.metadata.image}
dockercfg: ${artifact.source.dockerconfig}

createNamespace: false
namespace: poc

# Service Type allow you to specify what kind of service you want.
# Possible values for ServiceType are:
# ClusterIP | NodePort | LoadBalancer | ExternalName
serviceType: NodePort

# A Service can map an incoming port to any targetPort.
# targetPort is where application is listening on inside the container.
servicePort: 9090
serviceTargetPort: 9090

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    memory: 256Mi
  requests:
    cpu: 256m
    memory: 256Mi

env:
  config:
    SPRING_CONFIG_GIT_USERNAME: ${serviceVariable.SPRING_CONFIG_GIT_USERNAME}
    SPRING_CONFIG_GIT_URL: ${serviceVariable.SPRING_CONFIG_GIT_URL}
  secrets:
    SPRING_CONFIG_GIT_PASSWORD: ${serviceVariable.SPRING_CONFIG_GIT_PASSWORD}
  

